-- Master Tables
CREATE TABLE IF NOT EXISTS jobbers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sellers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendors (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transaction Tables (v2)
CREATE TABLE IF NOT EXISTS transactions_in (
    id SERIAL PRIMARY KEY,
    jobber_id INTEGER REFERENCES jobbers(id) ON DELETE CASCADE,
    seller_id INTEGER REFERENCES sellers(id) ON DELETE CASCADE,
    type1 NUMERIC DEFAULT 0,
    type2 NUMERIC DEFAULT 0,
    material VARCHAR(255),
    rate NUMERIC DEFAULT 0,
    amount NUMERIC DEFAULT 0,
    date DATE NOT NULL,
    remark TEXT,
    w BOOLEAN DEFAULT false,
    b BOOLEAN DEFAULT false,
    a BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions_out (
    id SERIAL PRIMARY KEY,
    jobber_id INTEGER REFERENCES jobbers(id) ON DELETE CASCADE,
    vendor_id INTEGER REFERENCES vendors(id) ON DELETE CASCADE,
    type1 NUMERIC DEFAULT 0,
    type2 NUMERIC DEFAULT 0,
    material VARCHAR(255),
    rate NUMERIC DEFAULT 0,
    amount NUMERIC DEFAULT 0,
    date DATE NOT NULL,
    remark TEXT,
    w BOOLEAN DEFAULT false,
    b BOOLEAN DEFAULT false,
    a BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Adjustments
CREATE TABLE IF NOT EXISTS jobber_adjustments (
    id SERIAL PRIMARY KEY,
    jobber_id INTEGER REFERENCES jobbers(id),
    amount NUMERIC NOT NULL,
    date DATE NOT NULL,
    remark TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seller_adjustments (
    id SERIAL PRIMARY KEY,
    seller_id INTEGER REFERENCES sellers(id),
    amount NUMERIC NOT NULL,
    date DATE NOT NULL,
    remark TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

